{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: surf_env3\
channels:\
  - r\
  - pyviz\
  - bokeh\
  - bioconda\
  - conda-forge\
  - defaults\
dependencies:\
  - rpy2=3.3.2\
  - pandas=1.1.0\
  - numpy=1.18.5\
  - scipy=1.5.2\
  - scikit-learn=0.23.1\
  - jupyter=1.0.0\
  - jupyter_bokeh=2.0.3\
  - jupyter_client=6.1.6\
  - jupyter_console=6.1.0\
  - jupyter_core=4.6.3\
  - jupyterlab=2.2.4\
  - jupyterlab_server=1.2.0\
  - gsl=2.6\
  - tzlocal=2.0.0\
  - simplegeneric=0.8.1\
  - natsort=0.7.1\
  - h5py=2.10.0\
  - tqdm=4.48.2\
  - patsy=0.5.1\
  - llvmlite=0.33.0\
  - numba=0.50.1\
  - joblib=0.16.0\
  - numexpr=2.7.1\
  - pytables=3.6.1\
  - python=3.8.5\
  - seaborn=0.10.1\
  - statsmodels=0.11.1\
  - python-igraph=0.7.1.post7\
  - leidenalg=0.7.0\
  - pip:\
    - fa2==0.3.5\
    - anndata==0.7.4\
    - anndata2ri==1.0.2\
    - gprofiler-official==1.0.0\
    - scanpy==1.5.1}